# Generated by Django 5.0.2 on 2025-01-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='XXX', max_length=3)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.stadium')),
                ('team_away', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_as_away', to='mainapp.team')),
                ('team_home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_as_home', to='mainapp.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_winner', to='mainapp.team')),
            ],
        ),
    ]
